version: '2'
services:
    vendorportal-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/vendorportal/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=vendorportal
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
